sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install -r requirements-dev.txt --use-wheel"
  - "pip install coveralls --use-wheel"
  - "python setup.py install"
script:
  - "flake8 go_http"
  - "py.test --cov=go_http go_http"
after_success:
  - coveralls
